[package]
name = "di-player"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.25.6"
rust-embed = "8.7.0"
tao = "0.33.0"
wry = "0.51.2"
dirs = "6.0.0"
muda = "0.16.1"
windows-sys = "0.59.0"

[build-dependencies]
tauri-winres = "0.3.0"