[package]
name = "di-player"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.25.2"
rust-embed = "8.5.0"
tao = "0.31.1"
wry = "0.48.0"
dirs = "5.0.1"
muda = "0.15.3"
windows-sys = "0.59.0"

[build-dependencies]
tauri-winres = "0.2.0"